app:
  init-props:
    is_recreate_server_user_needed: true
  message:
    lifespan: 86400000
#    lifespan: 10000
    path_to_attachments_folder: "C:\\wsp-attachments"



spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/whisper
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: false