app:
  init-props:
    fetch_props_from_db_at_startup: false
    is_recreate_server_user_needed: false
  message:
    lifespan: 86400000



spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/whisper
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: false